# GRU Gated Recurrent Unit
### Using libraries : $\textit{neupy}$

## Imports

 ![](gru.png)

In [2]:
from utilities.std_imports import *

from sklearn.model_selection import train_test_split
from neupy import algorithms, layers
from neupy.datasets import reber

## Testing

In [1]:
def add_padding(data):
    n_sampels = len(data)
    max_seq_length = max(map(len, data))

    data_matrix = np.zeros((n_sampels, max_seq_length))
    for i, sample in enumerate(data):
        data_matrix[i, -len(sample):] = sample

    return data_matrix


# An example of possible values for the `data` and `labels`
# variables
#
# >>> data
# array([array([1, 3, 1, 4]),
#        array([0, 3, 0, 3, 0, 4, 3, 0, 4, 4]),
#        array([0, 3, 0, 0, 3, 0, 4, 2, 4, 1, 0, 4, 0])], dtype=object)
# >>>
# >>> labels
# array([1, 0, 0])
data, labels = reber.make_reber_classification(
    n_samples=10000, return_indices=True)

# Shift all indices by 1. In the next row we will add zero
# paddings, so we need to make sure that we will not confuse
# paddings with zero indices.
data = data + 1

# Add paddings at the beggining of each vector to make sure
# that all samples has the same length. This trick allows to
# train network with multiple independent samples.
data = add_padding(data)

x_train, x_test, y_train, y_test = train_test_split(
    data, labels, test_size=0.2)

n_categories = len(reber.avaliable_letters) + 1  # +1 for zero paddings
n_time_steps = x_train.shape[1]

optimizer = algorithms.RMSProp(
    [
        layers.Input(n_time_steps),
        # shape: (n_samples, n_time_steps)

        layers.Embedding(n_categories, 10),
        # shape: (n_samples, n_time_steps, 10)

        # unroll_scan - speed up calculation for short sequences
        layers.GRU(20, unroll_scan=True),
        # shape: (n_samples, 20)

        layers.Sigmoid(1),
        # shape: (n_samples, 1)
    ],
    step=0.01,
    verbose=True,
    batch_size=64,
    loss='binary_crossentropy',
)
optimizer.train(x_train, y_train, x_test, y_test, epochs=20)

y_predicted = optimizer.predict(x_test).round()
accuracy = (y_predicted.T == y_test).mean()
print("Test accuracy: {:.2%}".format(accuracy))


Main information

[ALGORITHM] RMSProp

[OPTION] batch_size = 64
[OPTION] centered = False
[OPTION] decay = 0.95
[OPTION] epsilon = 1e-07
[OPTION] loss = binary_crossentropy
[OPTION] momentum = 0
[OPTION] regularizer = None
[OPTION] show_epoch = 1
[OPTION] shuffle_data = False
[OPTION] signals = None
[OPTION] step = 0.01
[OPTION] target = Tensor("placeholder/target/sigmoid-1:0", shape=(?, 1), dtype=float32)
[OPTION] verbose = True

[TENSORFLOW] Initializing Tensorflow variables and functions.


Time: 0:00:00 |N/A%|                            | ETA:  --:--:-- | loss: ------

[TENSORFLOW] Initialization finished successfully. It took 3.14 seconds


Time: 0:00:00 | 16%|####                         | ETA:  0:00:00 | loss:  0.189

#1 : [4 sec] train: 0.343149, valid: 0.344356


Time: 0:00:00 | 12%|###                          | ETA:  0:00:00 | loss: 0.0856

#2 : [998 ms] train: 0.106349, valid: 0.057297


Time: 0:00:00 | 18%|#####                        | ETA:  0:00:00 | loss: 0.0827

#3 : [1 sec] train: 0.034687, valid: 0.016380


Time: 0:00:00 | 18%|#####                        | ETA:  0:00:00 | loss: 0.0435

#4 : [988 ms] train: 0.001967, valid: 0.019819


Time: 0:00:00 | 19%|#####                       | ETA:  0:00:00 | loss: 0.00517

#5 : [1 sec] train: 0.001066, valid: 0.011488


Time: 0:00:00 | 18%|#####                        | ETA:  0:00:00 | loss: 0.0111

#6 : [984 ms] train: 0.000730, valid: 0.008852


Time: 0:00:00 | 18%|#####                       | ETA:  0:00:00 | loss: 0.00487

#7 : [1 sec] train: 0.000517, valid: 0.009283


Time: 0:00:00 | 18%|#####                       | ETA:  0:00:00 | loss: 0.00208

#8 : [1 sec] train: 0.000507, valid: 0.007454


Time: 0:00:00 | 18%|#####                       | ETA:  0:00:00 | loss: 0.00813

#9 : [984 ms] train: 0.000354, valid: 0.009593


Time: 0:00:00 | 18%|#####                       | ETA:  0:00:00 | loss: 0.00173

#10 : [979 ms] train: 0.000367, valid: 0.009420


Time: 0:00:00 | 18%|#####                       | ETA:  0:00:00 | loss: 0.00193

#11 : [973 ms] train: 0.000297, valid: 0.008050


Time: 0:00:00 | 18%|#####                       | ETA:  0:00:00 | loss: 0.00147

#12 : [989 ms] train: 0.000435, valid: 0.007933


Time: 0:00:00 | 18%|#####                       | ETA:  0:00:00 | loss: 0.00141

#13 : [974 ms] train: 0.000282, valid: 0.004870


Time: 0:00:00 | 18%|#####                       | ETA:  0:00:00 | loss: 0.00195

#14 : [971 ms] train: 0.000286, valid: 0.006322


Time: 0:00:00 | 18%|#####                       | ETA:  0:00:00 | loss: 0.00159

#15 : [974 ms] train: 0.000275, valid: 0.006127


Time: 0:00:00 | 18%|#####                       | ETA:  0:00:00 | loss: 0.00196

#16 : [987 ms] train: 0.000282, valid: 0.008022


Time: 0:00:00 | 18%|#####                       | ETA:  0:00:00 | loss: 0.00185

#17 : [997 ms] train: 0.000289, valid: 0.006787


Time: 0:00:00 | 18%|#####                       | ETA:  0:00:00 | loss: 0.00194

#18 : [993 ms] train: 0.000294, valid: 0.006212


Time: 0:00:00 | 18%|#####                       | ETA:  0:00:00 | loss: 0.00199

#19 : [997 ms] train: 0.000301, valid: 0.005733


Time: 0:00:00 |N/A%|                                           | ETA:  --:--:--

#20 : [1 sec] train: 0.000308, valid: 0.005574


Time: 0:00:00 | 71%|###############################             | ETA:  0:00:00

Test accuracy: 99.90%
